# backend/main.py
import os
import uvicorn
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from dotenv import load_dotenv

# Import our custom ML and Agent modules
from app.ml.plume_math import calculate_source_attribution
from app.agents.orchestrator import generate_enforcement_mandate
from app.ml.inference import get_grid_predictions, get_emission_sources, get_point_prediction, get_model_meta
from app import db
from datetime import datetime

# Load environment variables
load_dotenv()

# Initialize the FastAPI application
app = FastAPI(title="AeroShield IQ Core Engine")

@app.on_event("startup")
def _startup():
    db.init_db()

# Permit unrestricted operational data transit routes for local frontend dev iterations
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

class PredictionRequest(BaseModel):
    cell_id: int
    lat: float
    lon: float
    wind_speed: float
    wind_direction: float
    hour: int | None = None
    day_of_week: int | None = None

# --- ENDPOINTS ---

@app.post("/api/analyze-hotspot")
async def analyze_hotspot(payload: PredictionRequest):
    
    hour = payload.hour if payload.hour is not None else datetime.now().hour
    day_of_week = payload.day_of_week if payload.day_of_week is not None else datetime.now().weekday()

    # Dynamically load real Delhi emission sources generated by Step 2
    real_emission_sources = get_emission_sources()

    # 1. Compute plume back-propagation attribution profile
    #    (hour is passed through so the Pasquill stability class matches
    #    the one used to generate the prediction being explained)
    attribution_results = calculate_source_attribution(
        hotspot_lat=payload.lat,
        hotspot_lon=payload.lon,
        wind_speed=payload.wind_speed,
        wind_dir_deg=payload.wind_direction,
        sources_list=real_emission_sources,
        hour=hour,
    )
    primary_culprit = attribution_results[0] if attribution_results else {"name": "Unknown Diffuse Source"}

    # 2. Get the model's actual predicted PM2.5/AQI for this exact point
    #    instead of a hardcoded placeholder.
    point = get_point_prediction(
        lat=payload.lat, lon=payload.lon,
        wind_speed=payload.wind_speed, wind_direction=payload.wind_direction,
        hour=hour, day_of_week=day_of_week,
    )
    predicted_aqi = point["predicted_pm25"]

    # 3. Trigger AI Agent compliance generation pipeline
    enforcement_data = generate_enforcement_mandate(
        cell_id=payload.cell_id,
        aqi_value=predicted_aqi,
        primary_violator=primary_culprit["name"],
        attribution_matrix=attribution_results # Pass full matrix to LangGraph
    )

    return {
        "cell_id": payload.cell_id,
        "predicted_aqi": predicted_aqi,
        "aqi_category": point["aqi_category"],
        "attribution_matrix": attribution_results,
        "automated_mandate": enforcement_data
    }

@app.get("/api/city-grid")
async def city_grid_status(hour: int = 12, day_of_week: int = 1, month: int | None = None, wind_speed: float = 5.0, wind_direction: float = 120.0):
    """
    Returns full predictive spatial intelligence vectors for the frontend Mapbox renderer.
    `month` lets the frontend's date picker shift the seasonal features
    (winter stubble-burning peaks, monsoon washout, etc.) independently of
    hour-of-day. Wind is still a manually-set baseline, not a real
    multi-day forecast — see README for what that would take.
    """
    try:
        grid_data = get_grid_predictions(hour, day_of_week, wind_speed, wind_direction, month=month)
        
        # Package wind metadata so the frontend WindArrow renders correctly
        wind_meta = {
            "speed_ms": wind_speed,
            "direction_deg": wind_direction,
            "source": "Live Meteorological Baseline"
        }
        
        return {"status": "success", "grid": grid_data, "wind_meta": wind_meta}
    except Exception as e:
        return {"status": "error", "message": str(e)}


@app.get("/api/model-info")
async def model_info():
    """
    Feature #2: surfaces the LightGBM model's validation metrics
    (RMSE / MAE / within-15% accuracy) so the frontend can show a
    "Model: RMSE X · MAE Y" badge instead of asking people to trust it
    blindly. Populated by step3_etl_and_train.py's metrics block.
    """
    try:
        meta = get_model_meta()
        return {"status": "success", "meta": meta}
    except Exception as e:
        return {"status": "error", "message": str(e), "meta": {}}


class DispatchRequest(BaseModel):
    cell_id: int
    lat: float | None = None
    lon: float | None = None
    predicted_aqi: float | None = None
    aqi_label: str | None = None
    primary_violator: str | None = None
    confidence_score: float | None = None
    escalation_level: str | None = None
    dispatch_priority: str | None = None
    statute_violated: str | None = None
    legal_notice_draft: str | None = None
    case_summary: str | None = None
    attribution_matrix: list | None = None


@app.post("/api/dispatch")
async def dispatch_case(payload: DispatchRequest):
    """
    Feature #1: persists a dispatched enforcement case to SQLite so
    "Approve & Dispatch" survives a page refresh, instead of the old
    fake 1.8s setTimeout that forgot everything on reload.
    """
    try:
        case_id = db.insert_case(payload.model_dump())
        return {"status": "success", "case_id": case_id}
    except Exception as e:
        return {"status": "error", "message": str(e)}


@app.get("/api/cases")
async def get_cases(limit: int = 50):
    """Lists previously dispatched cases, most recent first."""
    try:
        return {"status": "success", "cases": db.list_cases(limit=limit)}
    except Exception as e:
        return {"status": "error", "message": str(e), "cases": []}

# --- SERVER START ---

if __name__ == "__main__":
    uvicorn.run("main:app", host="127.0.0.1", port=8000, reload=True)